name: pyconde2018 
channels:
  - anaconda
  - defaults
dependencies:
  - cairo=1.14.12=h8948797_3
  - fribidi=1.0.4=h14c3975_0
  - graphite2=1.3.11=h16798f4_2
  - graphviz=2.40.1=h21bd128_2
  - harfbuzz=1.8.4=hec2c2bc_0
  - libtiff=4.0.9=he85c1e1_1
  - pango=1.42.3=h8589676_0
  - backcall=0.1.0=py36_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_3
  - blas=1.0=mkl
  - bleach=2.1.3=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py36_0
  - cython=0.28.3=py36h14c3975_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_3
  - glib=2.56.1=h000015b_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_3
  - html5lib=1.0.1=py36_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_1
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.2.1=py36_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py36_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libgpuarray=0.7.6=h14c3975_0
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.6.0=hdbcaa40_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - mako=1.0.7=py36_0
  - markupsafe=1.0=py36h14c3975_1
  - mistune=0.8.3=py36h14c3975_1
  - mkl=2018.0.3=1
  - mkl-service=1.1.2=py36h90e4bf4_5
  - mkl_fft=1.0.2=py36h651fb7a_0
  - mkl_random=1.0.1=py36h4414c95_1
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=hf484d3e_0
  - notebook=5.5.0=py36_0
  - numpy=1.14.5=py36h1b885b7_4
  - numpy-base=1.14.5=py36hdbf6ddf_4
  - openssl=1.0.2p=h14c3975_0
  - pandoc=2.2.1=h629c226_0
  - pandocfilters=1.4.2=py36_1
  - parso=0.2.1=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - prompt_toolkit=1.0.15=py36_0
  - protobuf=3.6.0=py36hf484d3e_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.2.0=py36_0
  - pygpu=0.7.6=py36h035aef0_0
  - pyqt=5.9.2=py36h22d08a2_0
  - python=3.6.6=hc3d631a_0
  - python-dateutil=2.7.3=py36_0
  - pyzmq=17.0.0=py36h14c3975_3
  - qt=5.9.6=h52aff34_0
  - qtconsole=4.3.1=py36_0
  - readline=7.0=ha6073c6_4
  - scipy=1.1.0=py36hd20e5f9_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36_1
  - sqlite=3.24.0=h84994c4_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_0
  - theano=1.0.3=py36hfd86e86_0
  - tk=8.6.7=hc745277_3
  - tornado=5.0.2=py36h14c3975_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_0
  - zlib=1.2.11=ha838bed_2
prefix: /home/sidharth/miniconda3/envs/python3

